import { ActionType, CompositeType, ControlType, DeviceType } from '@core/lib/input/inputTypes';
import { defineScene } from './defineScene';

/**
 * Forest
 * Scene with realistic immersive forest environment with pond
 * Generated: 2025-10-10T00:00:00.000Z
 * Version: 3
 *
 * Pure data definition - all loading logic abstracted
 * Features: Enhanced realistic lighting with softer sun and atmospheric fog, natural material roughness,
 * varied tree heights and colors, expanded ground vegetation, fallen logs, mushrooms, ferns, and wildflowers.
 * Central pond with reflective water, lily pads, rocks around edge, and cattails/reeds.
 * Optimized shadow casting for performance. Designed for atmospheric depth and natural forest ambiance.
 */
export default defineScene({
  metadata: {
    name: 'Forest',
    version: 3,
    timestamp: '2025-10-10T00:00:00.000Z',
    author: 'scene-creator-agent',
    description:
      'Realistic immersive forest with natural lighting, atmospheric fog, varied vegetation, central pond with reflective water, and enhanced material realism',
  },
  entities: [
    {
      name: 'Main Camera',
      components: {
        Transform: {
          position: [0, 2, -15],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        Camera: {
          fov: 60,
          near: 0.1,
          far: 150,
          projectionType: 'perspective',
          orthographicSize: 10,
          depth: 0,
          isMain: true,
          clearFlags: 'skybox',
          skyboxTexture: '',
          backgroundColor: {
            r: 0.69,
            g: 0.77,
            b: 0.87,
            a: 1,
          },
          controlMode: 'free',
          viewportRect: {
            x: 0,
            y: 0,
            width: 1,
            height: 1,
          },
          hdr: true,
          toneMapping: 'aces',
          toneMappingExposure: 1.0,
          enablePostProcessing: true,
          postProcessingPreset: 'cinematic',
          enableSmoothing: true,
          followTarget: 0,
          followOffset: {
            x: 0,
            y: 2,
            z: -15,
          },
          smoothingSpeed: 3,
          rotationSmoothing: 2,
        },
      },
    },
    {
      name: 'Sun Light',
      components: {
        Transform: {
          position: [10, 15, 8],
          rotation: [-45, 30, 0],
          scale: [1, 1, 1],
        },
        Light: {
          lightType: 'directional',
          color: {
            r: 1.0,
            g: 0.92,
            b: 0.8,
          },
          intensity: 0.45,
          enabled: true,
          castShadow: true,
          directionX: -0.5,
          directionY: -0.8,
          directionZ: -0.3,
          range: 50,
          decay: 1,
          angle: 0.5235987901687622,
          penumbra: 0.2,
          shadowMapSize: 2048,
          shadowBias: -0.0001,
          shadowRadius: 2,
        },
      },
    },
    {
      name: 'Forest Ambient',
      components: {
        Transform: {
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        Light: {
          lightType: 'ambient',
          color: {
            r: 0.6,
            g: 0.7,
            b: 0.65,
          },
          intensity: 0.4,
          enabled: true,
          castShadow: false,
          directionX: 0,
          directionY: -1,
          directionZ: 0,
          range: 10,
          decay: 1,
          angle: 0.5235987901687622,
          penumbra: 0.1,
          shadowMapSize: 1024,
          shadowBias: -0.0001,
          shadowRadius: 1,
        },
      },
    },
    {
      name: 'Atmospheric Light',
      components: {
        Transform: {
          position: [0, 12, -8],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        Light: {
          lightType: 'point',
          color: {
            r: 0.9,
            g: 1,
            b: 0.85,
          },
          intensity: 0.15,
          enabled: true,
          castShadow: false,
          directionX: 0,
          directionY: -1,
          directionZ: 0,
          range: 25,
          decay: 2,
          angle: 0.5235987901687622,
          penumbra: 0.1,
          shadowMapSize: 1024,
          shadowBias: -0.0001,
          shadowRadius: 1,
        },
      },
    },
    {
      name: 'Forest Ground',
      components: {
        Transform: {
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        Terrain: {
          size: [100, 100],
          segments: [64, 64],
          heightScale: 3,
          noiseEnabled: true,
          noiseSeed: 12345,
          noiseFrequency: 0.05,
          noiseOctaves: 4,
          noisePersistence: 0.5,
          noiseLacunarity: 2,
        },
        MeshRenderer: {
          meshId: 'terrain',
          materialId: 'forest-ground',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#4a5c38',
            metalness: 0,
            roughness: 0.95,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 10,
            textureRepeatY: 10,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Pine Tree 1',
      components: {
        Transform: {
          position: [-8, 0, -5],
          rotation: [0, 15, 0],
          scale: [1.2, 1.5, 1.2],
        },
        MeshRenderer: {
          meshId: 'tree',
          materialId: 'pine-tree-1',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#2a4c14',
            metalness: 0,
            roughness: 0.92,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Oak Tree 1',
      components: {
        Transform: {
          position: [-12, 0, 3],
          rotation: [0, -25, 0],
          scale: [1.5, 1.2, 1.5],
        },
        MeshRenderer: {
          meshId: 'tree',
          materialId: 'oak-tree-1',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#385c1e',
            metalness: 0,
            roughness: 0.9,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Pine Tree 2',
      components: {
        Transform: {
          position: [10, 0, -3],
          rotation: [0, 45, 0],
          scale: [1.1, 1.4, 1.1],
        },
        MeshRenderer: {
          meshId: 'tree',
          materialId: 'pine-tree-2',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#2e5418',
            metalness: 0,
            roughness: 0.93,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Birch Tree 1',
      components: {
        Transform: {
          position: [7, 0, 4],
          rotation: [0, -10, 0],
          scale: [0.9, 1.0, 0.9],
        },
        MeshRenderer: {
          meshId: 'tree',
          materialId: 'birch-tree-1',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#527838',
            metalness: 0,
            roughness: 0.88,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Oak Tree 2',
      components: {
        Transform: {
          position: [-5, 0, 8],
          rotation: [0, 60, 0],
          scale: [1.4, 1.1, 1.4],
        },
        MeshRenderer: {
          meshId: 'tree',
          materialId: 'oak-tree-2',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#3c641f',
            metalness: 0,
            roughness: 0.91,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Pine Tree 3',
      components: {
        Transform: {
          position: [3, 0, 10],
          rotation: [0, -35, 0],
          scale: [1.0, 1.3, 1.0],
        },
        MeshRenderer: {
          meshId: 'tree',
          materialId: 'pine-tree-1',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#2a4c14',
            metalness: 0,
            roughness: 0.92,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Birch Tree 2',
      components: {
        Transform: {
          position: [0, 0, 12],
          rotation: [0, 90, 0],
          scale: [0.85, 1.2, 0.85],
        },
        MeshRenderer: {
          meshId: 'tree',
          materialId: 'birch-tree-2',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#568442',
            metalness: 0,
            roughness: 0.89,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Rock 1',
      components: {
        Transform: {
          position: [-3, 0.05, -2],
          rotation: [0, 25, 0],
          scale: [1.2, 0.8, 1.1],
        },
        MeshRenderer: {
          meshId: 'rock',
          materialId: 'rock-gray',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#6b7165',
            metalness: 0.05,
            roughness: 0.98,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Rock 2',
      components: {
        Transform: {
          position: [5, 0.08, 1],
          rotation: [0, -40, 0],
          scale: [0.9, 0.6, 0.95],
        },
        MeshRenderer: {
          meshId: 'rock',
          materialId: 'rock-brown',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#756e60',
            metalness: 0.05,
            roughness: 0.97,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Rock 3',
      components: {
        Transform: {
          position: [-6, 0.06, 6],
          rotation: [0, 70, 0],
          scale: [1.4, 0.7, 1.2],
        },
        MeshRenderer: {
          meshId: 'rock',
          materialId: 'rock-gray',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#6b7165',
            metalness: 0.05,
            roughness: 0.98,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Rock 4',
      components: {
        Transform: {
          position: [9, 0.07, -6],
          rotation: [0, 120, 0],
          scale: [0.7, 0.5, 0.8],
        },
        MeshRenderer: {
          meshId: 'rock',
          materialId: 'rock-brown',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#756e60',
            metalness: 0.05,
            roughness: 0.97,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Rock 5',
      components: {
        Transform: {
          position: [-11, 0.05, -3],
          rotation: [0, 85, 0],
          scale: [0.6, 0.55, 0.7],
        },
        MeshRenderer: {
          meshId: 'rock',
          materialId: 'rock-gray',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#6b7165',
            metalness: 0.05,
            roughness: 0.98,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Rock 6',
      components: {
        Transform: {
          position: [2.5, 0.06, 7],
          rotation: [0, -55, 0],
          scale: [0.8, 0.6, 0.85],
        },
        MeshRenderer: {
          meshId: 'rock',
          materialId: 'rock-brown',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#756e60',
            metalness: 0.05,
            roughness: 0.97,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Rock 7',
      components: {
        Transform: {
          position: [-1.5, 0.08, -7.5],
          rotation: [0, 165, 0],
          scale: [1.1, 0.65, 1.0],
        },
        MeshRenderer: {
          meshId: 'rock',
          materialId: 'rock-gray',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#6b7165',
            metalness: 0.05,
            roughness: 0.98,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Bush 1',
      components: {
        Transform: {
          position: [-4, 0, 2],
          rotation: [0, 0, 0],
          scale: [1.1, 1.0, 1.1],
        },
        MeshRenderer: {
          meshId: 'bush',
          materialId: 'forest-bush',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#4a7c59',
            metalness: 0,
            roughness: 0.92,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Bush 2',
      components: {
        Transform: {
          position: [2, 0, -1],
          rotation: [0, 45, 0],
          scale: [0.9, 0.9, 0.9],
        },
        MeshRenderer: {
          meshId: 'bush',
          materialId: 'forest-bush',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#4a7c59',
            metalness: 0,
            roughness: 0.92,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Bush 3',
      components: {
        Transform: {
          position: [8, 0, 7],
          rotation: [0, -20, 0],
          scale: [1.2, 1.1, 1.2],
        },
        MeshRenderer: {
          meshId: 'bush',
          materialId: 'forest-bush',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#4a7c59',
            metalness: 0,
            roughness: 0.92,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Forest Bush 4',
      components: {
        Transform: {
          position: [-9, 0, -1],
          rotation: [0, 60, 0],
          scale: [1.0, 1.0, 1.0],
        },
        MeshRenderer: {
          meshId: 'bush',
          materialId: 'forest-bush',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#4a7c59',
            metalness: 0,
            roughness: 0.92,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Player Spawn Point',
      components: {
        Transform: {
          position: [0, 1, -10],
          rotation: [0, 0, 0],
          scale: [0.5, 2, 0.5],
        },
        MeshRenderer: {
          meshId: 'cube',
          materialId: 'spawn-marker',
          enabled: false,
          castShadows: false,
          receiveShadows: false,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#00ff00',
            metalness: 0,
            roughness: 0.5,
            emissive: '#00ff00',
            emissiveIntensity: 0.5,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 1',
      components: {
        Transform: {
          position: [-2, 0.05, -3],
          rotation: [0, 12, 0],
          scale: [0.4, 0.3, 0.4],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 2',
      components: {
        Transform: {
          position: [4, 0.08, 2],
          rotation: [0, -35, 0],
          scale: [0.5, 0.35, 0.5],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 3',
      components: {
        Transform: {
          position: [-7, 0.06, 1],
          rotation: [0, 58, 0],
          scale: [0.45, 0.32, 0.45],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 4',
      components: {
        Transform: {
          position: [6, 0.07, -5],
          rotation: [0, 22, 0],
          scale: [0.38, 0.28, 0.38],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 5',
      components: {
        Transform: {
          position: [-1, 0.09, 5],
          rotation: [0, -48, 0],
          scale: [0.52, 0.4, 0.52],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 6',
      components: {
        Transform: {
          position: [9, 0.05, 3],
          rotation: [0, 72, 0],
          scale: [0.42, 0.33, 0.42],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 7',
      components: {
        Transform: {
          position: [-10, 0.08, -4],
          rotation: [0, -15, 0],
          scale: [0.48, 0.36, 0.48],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 8',
      components: {
        Transform: {
          position: [1, 0.07, 9],
          rotation: [0, 85, 0],
          scale: [0.55, 0.42, 0.55],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 9',
      components: {
        Transform: {
          position: [5.5, 0.06, -8],
          rotation: [0, 102, 0],
          scale: [0.44, 0.34, 0.44],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 10',
      components: {
        Transform: {
          position: [-4.5, 0.09, 9.5],
          rotation: [0, -72, 0],
          scale: [0.49, 0.38, 0.49],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 11',
      components: {
        Transform: {
          position: [11, 0.05, 0.5],
          rotation: [0, 138, 0],
          scale: [0.41, 0.31, 0.41],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 12',
      components: {
        Transform: {
          position: [-8.5, 0.08, -7],
          rotation: [0, -118, 0],
          scale: [0.47, 0.36, 0.47],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 13',
      components: {
        Transform: {
          position: [7.5, 0.06, 10],
          rotation: [0, 52, 0],
          scale: [0.43, 0.32, 0.43],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Grass Patch 14',
      components: {
        Transform: {
          position: [0.5, 0.07, -5.5],
          rotation: [0, -88, 0],
          scale: [0.46, 0.35, 0.46],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'grass',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#5a8c3a',
            metalness: 0,
            roughness: 0.96,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Wildflower Yellow 1',
      components: {
        Transform: {
          position: [-3.5, 0, 0],
          rotation: [0, 45, 0],
          scale: [0.25, 0.3, 0.25],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'flower-yellow',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#e8c545',
            metalness: 0,
            roughness: 0.65,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Wildflower Purple 1',
      components: {
        Transform: {
          position: [3.2, 0, 5.5],
          rotation: [0, -28, 0],
          scale: [0.22, 0.28, 0.22],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'flower-purple',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#8a2498',
            metalness: 0,
            roughness: 0.65,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Wildflower White 1',
      components: {
        Transform: {
          position: [5.8, 0, -1.2],
          rotation: [0, 62, 0],
          scale: [0.2, 0.26, 0.2],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'flower-white',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#f0f0f0',
            metalness: 0,
            roughness: 0.65,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Wildflower Yellow 2',
      components: {
        Transform: {
          position: [-8.5, 0, 4],
          rotation: [0, -12, 0],
          scale: [0.24, 0.29, 0.24],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'flower-yellow',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#e8c545',
            metalness: 0,
            roughness: 0.65,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fallen Log 1',
      components: {
        Transform: {
          position: [-5.5, 0.05, -3.5],
          rotation: [0, 35, 90],
          scale: [0.6, 3.5, 0.6],
        },
        MeshRenderer: {
          meshId: 'cylinder',
          materialId: 'bark-brown',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#3a2818',
            metalness: 0,
            roughness: 0.98,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fallen Log 2',
      components: {
        Transform: {
          position: [7.2, 0.08, 8.5],
          rotation: [0, -65, 90],
          scale: [0.55, 4.2, 0.55],
        },
        MeshRenderer: {
          meshId: 'cylinder',
          materialId: 'bark-brown',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#3a2818',
            metalness: 0,
            roughness: 0.98,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fallen Branch 1',
      components: {
        Transform: {
          position: [4.8, 0.06, -7.2],
          rotation: [0, 125, 90],
          scale: [0.35, 2.1, 0.35],
        },
        MeshRenderer: {
          meshId: 'cylinder',
          materialId: 'bark-brown',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#3a2818',
            metalness: 0,
            roughness: 0.98,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fallen Branch 2',
      components: {
        Transform: {
          position: [-9.5, 0.07, 8],
          rotation: [0, -82, 90],
          scale: [0.4, 2.8, 0.4],
        },
        MeshRenderer: {
          meshId: 'cylinder',
          materialId: 'bark-brown',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#3a2818',
            metalness: 0,
            roughness: 0.98,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fallen Branch 3',
      components: {
        Transform: {
          position: [1.2, 0.05, 3.8],
          rotation: [0, 15, 90],
          scale: [0.32, 1.9, 0.32],
        },
        MeshRenderer: {
          meshId: 'cylinder',
          materialId: 'bark-brown',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#3a2818',
            metalness: 0,
            roughness: 0.98,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Mushroom Cluster 1',
      components: {
        Transform: {
          position: [-8.2, 0, -4.8],
          rotation: [0, 18, 0],
          scale: [0.18, 0.22, 0.18],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'mushroom',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#e8d8b8',
            metalness: 0,
            roughness: 0.75,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Mushroom Cluster 2',
      components: {
        Transform: {
          position: [-11.8, 0, 3.2],
          rotation: [0, -42, 0],
          scale: [0.15, 0.19, 0.15],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'mushroom',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#e8d8b8',
            metalness: 0,
            roughness: 0.75,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Mushroom Cluster 3',
      components: {
        Transform: {
          position: [10.2, 0, -2.8],
          rotation: [0, 55, 0],
          scale: [0.2, 0.24, 0.2],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'mushroom',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#e8d8b8',
            metalness: 0,
            roughness: 0.75,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fern 1',
      components: {
        Transform: {
          position: [-6.5, 0, -1.5],
          rotation: [0, 25, 0],
          scale: [0.65, 0.7, 0.65],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'fern',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#2d5016',
            metalness: 0,
            roughness: 0.94,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fern 2',
      components: {
        Transform: {
          position: [4.5, 0, 6.2],
          rotation: [0, -38, 0],
          scale: [0.58, 0.65, 0.58],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'fern',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#2d5016',
            metalness: 0,
            roughness: 0.94,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fern 3',
      components: {
        Transform: {
          position: [-10.5, 0, 7],
          rotation: [0, 72, 0],
          scale: [0.72, 0.78, 0.72],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'fern',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#2d5016',
            metalness: 0,
            roughness: 0.94,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fern 4',
      components: {
        Transform: {
          position: [8.8, 0, -4.5],
          rotation: [0, -15, 0],
          scale: [0.62, 0.68, 0.62],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'fern',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#2d5016',
            metalness: 0,
            roughness: 0.94,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Fern 5',
      components: {
        Transform: {
          position: [0.8, 0, 11.5],
          rotation: [0, 48, 0],
          scale: [0.68, 0.74, 0.68],
        },
        MeshRenderer: {
          meshId: 'sphere',
          materialId: 'fern',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
          material: {
            shader: 'standard',
            materialType: 'solid',
            color: '#2d5016',
            metalness: 0,
            roughness: 0.94,
            emissive: '#000000',
            emissiveIntensity: 0,
            normalScale: 1,
            occlusionStrength: 1,
            textureOffsetX: 0,
            textureOffsetY: 0,
            textureRepeatX: 1,
            textureRepeatY: 1,
            albedoTexture: '',
            normalTexture: '',
            metallicTexture: '',
            roughnessTexture: '',
            emissiveTexture: '',
            occlusionTexture: '',
          },
        },
      },
    },
    {
      name: 'Pond Water',
      components: {
        Transform: {
          position: [0, 0.02, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        CustomShape: {
          shapeId: 'pond-water',
          params: {
            radius: 3,
            height: 0.05,
            radialSegments: 32,
          },
        },
        MeshRenderer: {
          meshId: 'customShape',
          materialId: 'pond-water',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
        },
      },
    },
    {
      name: 'Lily Pads',
      components: {
        Transform: {
          position: [0, 0.05, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        CustomShape: {
          shapeId: 'lily-pads',
          params: {
            count: 4,
            padRadius: 0.25,
            padHeight: 0.02,
            spreadRadius: 2.5,
            radialSegments: 16,
            randomSeed: 42,
          },
        },
        MeshRenderer: {
          meshId: 'customShape',
          materialId: 'lily-pad',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
        },
      },
    },
    {
      name: 'Pond Rocks Gray',
      components: {
        Transform: {
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        CustomShape: {
          shapeId: 'pond-rocks-gray',
          params: {
            count: 2,
            rockSize: 0.6,
            spreadRadius: 2.8,
            randomSeed: 42,
            detail: 0,
          },
        },
        MeshRenderer: {
          meshId: 'customShape',
          materialId: 'rock-gray',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
        },
      },
    },
    {
      name: 'Pond Rocks Brown',
      components: {
        Transform: {
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        CustomShape: {
          shapeId: 'pond-rocks-brown',
          params: {
            count: 2,
            rockSize: 0.6,
            spreadRadius: 2.8,
            randomSeed: 43,
            detail: 0,
          },
        },
        MeshRenderer: {
          meshId: 'customShape',
          materialId: 'rock-brown',
          enabled: true,
          castShadows: true,
          receiveShadows: true,
          modelPath: '',
        },
      },
    },
    {
      name: 'Cattail Reeds',
      components: {
        Transform: {
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        CustomShape: {
          shapeId: 'cattail-reeds',
          params: {
            count: 4,
            reedRadius: 0.04,
            reedHeight: 1.2,
            spreadRadius: 2.5,
            randomSeed: 42,
          },
        },
        MeshRenderer: {
          meshId: 'customShape',
          materialId: 'reed-stem',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
        },
      },
    },
    {
      name: 'Cattail Heads',
      components: {
        Transform: {
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: [1, 1, 1],
        },
        CustomShape: {
          shapeId: 'cattail-heads',
          params: {
            count: 4,
            reedHeight: 1.2,
            headRadius: 0.06,
            headHeight: 0.25,
            spreadRadius: 2.5,
            randomSeed: 42,
          },
        },
        MeshRenderer: {
          meshId: 'customShape',
          materialId: 'cattail-head',
          enabled: true,
          castShadows: false,
          receiveShadows: true,
          modelPath: '',
        },
      },
    },
  ],
  materials: [
    {
      id: 'default',
      name: 'Default Material',
      shader: 'standard',
      materialType: 'solid',
      color: '#cccccc',
      metalness: 0,
      roughness: 0.7,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'forest-ground',
      name: 'Forest Ground',
      shader: 'standard',
      materialType: 'solid',
      color: '#4a5c38',
      metalness: 0,
      roughness: 0.95,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 10,
      textureRepeatY: 10,
    },
    {
      id: 'pine-tree-1',
      name: 'Pine Tree Variant 1',
      shader: 'standard',
      materialType: 'solid',
      color: '#2a4c14',
      metalness: 0,
      roughness: 0.92,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'pine-tree-2',
      name: 'Pine Tree Variant 2',
      shader: 'standard',
      materialType: 'solid',
      color: '#2e5418',
      metalness: 0,
      roughness: 0.93,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'oak-tree-1',
      name: 'Oak Tree Variant 1',
      shader: 'standard',
      materialType: 'solid',
      color: '#385c1e',
      metalness: 0,
      roughness: 0.9,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'oak-tree-2',
      name: 'Oak Tree Variant 2',
      shader: 'standard',
      materialType: 'solid',
      color: '#3c641f',
      metalness: 0,
      roughness: 0.91,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'birch-tree-1',
      name: 'Birch Tree Variant 1',
      shader: 'standard',
      materialType: 'solid',
      color: '#527838',
      metalness: 0,
      roughness: 0.88,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'birch-tree-2',
      name: 'Birch Tree Variant 2',
      shader: 'standard',
      materialType: 'solid',
      color: '#568442',
      metalness: 0,
      roughness: 0.89,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'rock-gray',
      name: 'Gray Forest Rock',
      shader: 'standard',
      materialType: 'solid',
      color: '#6b7165',
      metalness: 0.05,
      roughness: 0.98,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'rock-brown',
      name: 'Brown Forest Rock',
      shader: 'standard',
      materialType: 'solid',
      color: '#756e60',
      metalness: 0.05,
      roughness: 0.97,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'forest-bush',
      name: 'Forest Bush',
      shader: 'standard',
      materialType: 'solid',
      color: '#4a7c59',
      metalness: 0,
      roughness: 0.92,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'spawn-marker',
      name: 'Spawn Point Marker',
      shader: 'standard',
      materialType: 'solid',
      color: '#00ff00',
      metalness: 0,
      roughness: 0.5,
      emissive: '#00ff00',
      emissiveIntensity: 0.5,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'grass',
      name: 'Grass Patch',
      shader: 'standard',
      materialType: 'solid',
      color: '#5a8c3a',
      metalness: 0,
      roughness: 0.96,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'flower-yellow',
      name: 'Yellow Wildflower',
      shader: 'standard',
      materialType: 'solid',
      color: '#e8c545',
      metalness: 0,
      roughness: 0.65,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'flower-purple',
      name: 'Purple Wildflower',
      shader: 'standard',
      materialType: 'solid',
      color: '#8a2498',
      metalness: 0,
      roughness: 0.65,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'flower-white',
      name: 'White Wildflower',
      shader: 'standard',
      materialType: 'solid',
      color: '#f0f0f0',
      metalness: 0,
      roughness: 0.65,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'bark-brown',
      name: 'Fallen Log Bark',
      shader: 'standard',
      materialType: 'solid',
      color: '#3a2818',
      metalness: 0,
      roughness: 0.98,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'mushroom',
      name: 'Forest Mushroom',
      shader: 'standard',
      materialType: 'solid',
      color: '#e8d8b8',
      metalness: 0,
      roughness: 0.75,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'fern',
      name: 'Forest Fern',
      shader: 'standard',
      materialType: 'solid',
      color: '#2d5016',
      metalness: 0,
      roughness: 0.94,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'pond-water',
      name: 'Pond Water',
      shader: 'standard',
      materialType: 'solid',
      color: '#3a7c8f',
      metalness: 0.1,
      roughness: 0.15,
      emissive: '#0a1a2a',
      emissiveIntensity: 0.05,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'lily-pad',
      name: 'Lily Pad',
      shader: 'standard',
      materialType: 'solid',
      color: '#3a6e2f',
      metalness: 0,
      roughness: 0.7,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'reed-stem',
      name: 'Cattail Reed Stem',
      shader: 'standard',
      materialType: 'solid',
      color: '#4a5c2e',
      metalness: 0,
      roughness: 0.9,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
    {
      id: 'cattail-head',
      name: 'Cattail Head',
      shader: 'standard',
      materialType: 'solid',
      color: '#5c3a1e',
      metalness: 0,
      roughness: 0.85,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
      textureRepeatX: 1,
      textureRepeatY: 1,
    },
  ],
  prefabs: [],
  inputAssets: [
    {
      name: 'Forest Controls',
      controlSchemes: [
        {
          name: 'Keyboard & Mouse',
          deviceRequirements: [
            {
              deviceType: DeviceType.Keyboard,
              optional: false,
            },
            {
              deviceType: DeviceType.Mouse,
              optional: true,
            },
          ],
        },
        {
          name: 'Gamepad',
          deviceRequirements: [
            {
              deviceType: DeviceType.Gamepad,
              optional: false,
            },
          ],
        },
      ],
      actionMaps: [
        {
          name: 'Gameplay',
          enabled: true,
          actions: [
            {
              name: 'Move',
              actionType: ActionType.PassThrough,
              controlType: ControlType.Vector2,
              enabled: true,
              bindings: [
                {
                  compositeType: CompositeType.TwoDVector,
                  bindings: {
                    up: {
                      type: DeviceType.Keyboard,
                      path: 'w',
                    },
                    down: {
                      type: DeviceType.Keyboard,
                      path: 's',
                    },
                    left: {
                      type: DeviceType.Keyboard,
                      path: 'a',
                    },
                    right: {
                      type: DeviceType.Keyboard,
                      path: 'd',
                    },
                  },
                },
                {
                  compositeType: CompositeType.TwoDVector,
                  bindings: {
                    up: {
                      type: DeviceType.Keyboard,
                      path: 'arrowup',
                    },
                    down: {
                      type: DeviceType.Keyboard,
                      path: 'arrowdown',
                    },
                    left: {
                      type: DeviceType.Keyboard,
                      path: 'arrowleft',
                    },
                    right: {
                      type: DeviceType.Keyboard,
                      path: 'arrowright',
                    },
                  },
                },
              ],
            },
            {
              name: 'Jump',
              actionType: ActionType.Button,
              controlType: ControlType.Button,
              enabled: true,
              bindings: [
                {
                  type: DeviceType.Keyboard,
                  path: 'space',
                },
              ],
            },
            {
              name: 'Look',
              actionType: ActionType.PassThrough,
              controlType: ControlType.Vector2,
              enabled: true,
              bindings: [
                {
                  type: DeviceType.Mouse,
                  path: 'delta',
                },
              ],
            },
            {
              name: 'Sprint',
              actionType: ActionType.Button,
              controlType: ControlType.Button,
              enabled: true,
              bindings: [
                {
                  type: DeviceType.Keyboard,
                  path: 'shift',
                },
              ],
            },
          ],
        },
        {
          name: 'UI',
          enabled: true,
          actions: [
            {
              name: 'Navigate',
              actionType: ActionType.PassThrough,
              controlType: ControlType.Vector2,
              enabled: true,
              bindings: [
                {
                  compositeType: CompositeType.TwoDVector,
                  bindings: {
                    up: {
                      type: DeviceType.Keyboard,
                      path: 'arrowup',
                    },
                    down: {
                      type: DeviceType.Keyboard,
                      path: 'arrowdown',
                    },
                    left: {
                      type: DeviceType.Keyboard,
                      path: 'arrowleft',
                    },
                    right: {
                      type: DeviceType.Keyboard,
                      path: 'arrowright',
                    },
                  },
                },
              ],
            },
            {
              name: 'Submit',
              actionType: ActionType.Button,
              controlType: ControlType.Button,
              enabled: true,
              bindings: [
                {
                  type: DeviceType.Keyboard,
                  path: 'enter',
                },
                {
                  type: DeviceType.Keyboard,
                  path: 'space',
                },
              ],
            },
            {
              name: 'Cancel',
              actionType: ActionType.Button,
              controlType: ControlType.Button,
              enabled: true,
              bindings: [
                {
                  type: DeviceType.Keyboard,
                  path: 'escape',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
});
